// Maps the backend `dub_clips` (the timeline's source of truth) to the editor's
// visual `Clip` type, and routes a clip edit back to the right persistence:
//   - dub:video   → project video lead-in (setVideoOffset)
//   - dub:tts/sub → the segment's offset (setSegmentOffset)
//   - dub:banner  → the overlay's range (patchOverlay)
//   - user        → the clip itself (updateClip)
// Dub-origin clips are regenerated by compose, so their drags persist on the
// underlying dub entity; user clips persist directly.

import type { DubClip, DubDetail } from "../../studioApi";
import type { Clip, ClipType } from "./types";

/** Timeline track key for a clip — dub clips reuse the known keys so the existing
 *  gutter/track controls keep working; user clips get a generic per-layer key. */
export function trackKeyOf(c: DubClip): string {
  if (c.origin.startsWith("dub:video")) return "V1";
  if (c.origin.startsWith("dub:tts")) return "TTS";
  if (c.origin.startsWith("dub:sub")) return "SVI";
  if (c.origin.startsWith("dub:banner")) return "IMG";
  // user clip → its own layer, keyed by kind + track index
  const prefix = c.kind === "video" ? "UV" : c.kind === "audio" ? "UA" : c.kind === "image" ? "UI" : "UT";
  return `${prefix}${c.track}`;
}

const editorType = (kind: string): ClipType =>
  kind === "text" ? "sub" : (kind as ClipType);

function nameOf(c: DubClip): string {
  if (c.kind === "text") return c.text || "(văn bản)";
  if (c.origin.startsWith("dub:video")) return "Video";
  if (c.origin.startsWith("dub:tts")) return "Giọng lồng";
  if (c.origin.startsWith("dub:banner")) return "Banner";
  if (c.source) {
    const base = c.source.split(/[\\/]/).pop() || "media";
    return base;
  }
  return c.kind;
}

/** Build the editor timeline clips from the project's dub_clips. */
export function clipsToEditor(detail: DubDetail | null): Clip[] {
  if (!detail) return [];
  return detail.clips.map((c) => ({
    id: c.id,
    track: trackKeyOf(c),
    type: editorType(c.kind),
    name: nameOf(c),
    start: c.start_s,
    dur: Math.max(0.1, c.dur_s),
    opacity: Math.round(c.opacity * 100),
    vol: Math.round(c.volume * 100),
    ox: c.x * 100,
    oy: c.y * 100,
    text: c.kind === "text" ? (c.text ?? "") : undefined,
    kind: c.kind === "audio" ? (c.origin.startsWith("dub:tts") ? "tts" : "music") : undefined,
  }));
}

/** A signature that changes only when the clips (or their geometry) change. */
export function clipsSignature(detail: DubDetail | null): string {
  if (!detail) return "none";
  return detail.clips
    .map((c) => `${c.id}:${c.track}:${c.start_s.toFixed(2)}:${c.dur_s.toFixed(2)}:${c.x.toFixed(3)}:${c.y.toFixed(3)}:${c.w.toFixed(3)}:${c.opacity.toFixed(2)}:${(c.text ?? "").length}`)
    .join("|");
}

export function clipById(detail: DubDetail | null, id: string): DubClip | undefined {
  return detail?.clips.find((c) => c.id === id);
}
